version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    steps: 
      - checkout
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Installing gh-pages
          command: npm install gh-pages
      - run:
          name: Remove dist pakage
          command: rm -rf dist
      - run: 
          name: Building a projeck
          command: npm parcel build ./index.html  --public-url /Lesson6
      - run: 
          name: Push to Github Pages
          command: npm run gh-pages -d dist
  
    
    