version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    steps: 
      - checkout
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Installing gh-pages
          command: mkdir ~/.npm-global
      - run: npm config set prefix '~/.npm-global'
      - run: export PATH=~/.npm-global/bin:$PATH
      - run: source ~/.profile
      - run: npm install -g gh-pages
      - run:
          name: Remove dist pakage
          command: rm -rf dist
      - run: 
          name: Building a projeck
          command: npm run build
      - run: 
          name: Push to Github Pages
          command: npm gh-pages -d dist
  
    
    