version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    steps: 
      - checkout
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Installing gh-pages and parcel
          command: sudo npm install -g gh-pages parcel
      - run: 
          name: Building a project
          command: |-
              rm -rf dist
              parcel build ./index.html  --public-url /Lesson6
      - run: |- 
            git config user.email "ikharlamov21@gmail.com"
            git config user.name "Kharya1337"
      - run: 
          name: Push to Github Pages
          command: gh-pages -d dist
  
    
    