version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    steps: 
      - checkout
      - run: 
          name: Installing the modules
          command: npm install
      - run:
          name: Linter
          command: npm run lint
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deploy:
    steps: 
      - run:
          name: Installing gh-pages
          command: npm install gh-pages
      - run:
          name: Build a project
          command: npm run rm -rf dist && parcel build ./index.html  --public-url /illya-interns-work
      - run: 
          name: Push to Github Pages
          command: npm run gh-pages -d dist
  
    
    