version: 2
jobs: 
  task1.1:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ../1.2
    steps: 
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Linter
          command: npm run lint
      - run: 
          name: Building a project
          command: npm run build
  task1.2:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ../1.1
    steps: 
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Linter
          command: npm run lint
      - run: 
          name: Building a project
          command: npm run build
workflows:
  version: 2
  first_second:
    jobs:
      - task1.1
      - task1.2


  
    
    