version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    steps: 
      - checkout
      - run: 
          name: Installing the modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Installing gh-pages
          command: sudo npm install -g gh-pages
      - run:
          name: Remove dist pakage
          command: rm -rf dist
      - run: 
          name: Building a projeck
          command: npm run build
      - run: git config --global user.email "you@example.com"
             git config --global user.name "Your Name"
      - run: 
          name: Push to Github Pages
          command: gh-pages -d dist
  
    
    